-- AlterTable
ALTER TABLE "Activity" ADD COLUMN     "claimed" BOOLEAN DEFAULT false,
ADD COLUMN     "equityDetails" TEXT[],
ADD COLUMN     "equityTitle" TEXT,
ADD COLUMN     "externalLinks" JSONB,
ADD COLUMN     "externalLinksTitle" TEXT,
ADD COLUMN     "nftDescription" TEXT,
ADD COLUMN     "nftImage" TEXT,
ADD COLUMN     "nftName" TEXT,
ADD COLUMN     "nftPrice" DOUBLE PRECISION,
ADD COLUMN     "nftTotalSupply" INTEGER,
ADD COLUMN     "nftUsageRules" TEXT,
ADD COLUMN     "nftValidityEnd" TIMESTAMP(3),
ADD COLUMN     "nftValidityStart" TIMESTAMP(3),
ADD COLUMN     "remaining" INTEGER,
ADD COLUMN     "showInExplore" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "statusNote" TEXT,
ADD COLUMN     "total" INTEGER,
ADD COLUMN     "type" TEXT NOT NULL DEFAULT 'MEMBERSHIP';
