services:
  ddc-backend-api:
    platform: linux/arm64/v8
    build: .                # 用本地 Dockerfile 构建镜像
    ports:
      - "127.0.0.1:10000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src      # 挂载本地 src 目录到容器
      - ./prisma:/app/prisma
      - ./keys:/app/keys
      - ./scripts:/app/scripts
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: npm run dev  # 使用 nodemon 启动，使代码更新无需重建镜像即可生效
    networks:
      - backend_network
    restart: always
    depends_on:
      - ddc-backend-db

  ddc-backend-db:
    image: postgres:17
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:15432:5432"
    environment:
      - POSTGRES_USER=ddc
      - POSTGRES_PASSWORD=ddc
      - POSTGRES_DB=ddc
    restart: always
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
