const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const prisma = require('../utils/prisma');

const INVOICE_DIR = path.join(__dirname, '../../public/assets/commerce/invoices');
const LOGO_PATH = path.join(__dirname, '../../public/assets/logos/datadance-official.png');
/** Bump when layout/branding changes so cached PDFs regenerate. */
const PDF_LAYOUT_VERSION = 'v2';

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function money(amount) {
  const value = Number(amount || 0).toFixed(2);
  return `USD ${value}`;
}

function formatDate(value) {
  if (!value) return '-';
  return new Date(value).toISOString().slice(0, 10);
}

function partyBlock(party = {}) {
  return [
    party.companyName || '-',
    party.brNumber || party.taxId ? `BR / Tax ID: ${party.brNumber || party.taxId}` : null,
    party.address || null,
    party.country || null,
    party.email || null,
    party.bankName ? `Bank: ${party.bankName}` : null,
    party.bankAccount ? `Account: ${party.bankAccount}` : null,
  ].filter(Boolean);
}

function drawHeader(doc) {
  const left = 48;
  const top = 40;
  const logoSize = 52;

  if (fs.existsSync(LOGO_PATH)) {
    doc.image(LOGO_PATH, left, top, { width: logoSize, height: logoSize });
  }

  const textX = left + logoSize + 14;
  doc.fontSize(20).fillColor('#111111').text('Commercial Invoice', textX, top + 6, {
    width: 400,
  });
  doc.fontSize(10).fillColor('#555555').text('DataDance Technology Ltd. · B-end data licence', textX, top + 32, {
    width: 400,
  });
  doc.y = Math.max(doc.y, top + logoSize + 18);
  doc.x = left;
}

async function generateInvoicePdf(invoice) {
  ensureDir(INVOICE_DIR);
  const filename = `${invoice.invoiceNumber}.${PDF_LAYOUT_VERSION}.pdf`;
  const absolutePath = path.join(INVOICE_DIR, filename);
  const publicPath = `/assets/commerce/invoices/${filename}`;

  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const stream = fs.createWriteStream(absolutePath);
    doc.pipe(stream);

    drawHeader(doc);
    doc.moveDown(0.6);

    doc.fontSize(11).fillColor('#111111');
    doc.text(`Invoice No.  ${invoice.invoiceNumber}`);
    doc.text(`Order No.    ${invoice.order?.orderNumber || '-'}`);
    doc.text(`Issue Date   ${formatDate(invoice.issueDate)}`);
    doc.text(`Due Date     ${formatDate(invoice.dueDate)}`);
    doc.text(`Currency     ${invoice.currency || 'USD'}`);
    doc.text(`Payment Terms ${invoice.paymentTerms || 'Due on receipt'}`);
    doc.text(`Status       ${String(invoice.status || '').toUpperCase()}`);
    doc.moveDown(1);

    const sellerY = doc.y;
    doc.fontSize(12).fillColor('#008C85').text('Seller / Issuer', 48, sellerY);
    doc.fontSize(10).fillColor('#111111');
    partyBlock(invoice.sellerSnapshot).forEach((line) => doc.text(line, 48));

    const buyerX = 320;
    doc.fontSize(12).fillColor('#008C85').text('Buyer / Bill To', buyerX, sellerY);
    doc.fontSize(10).fillColor('#111111');
    doc.y = sellerY + 16;
    partyBlock(invoice.buyerSnapshot).forEach((line) => doc.text(line, buyerX));

    doc.moveDown(2);
    doc.x = 48;
    doc.fontSize(12).fillColor('#008C85').text('Itemized Service List');
    doc.moveDown(0.5);

    const tableTop = doc.y;
    const columns = [
      { label: 'Description', x: 48, width: 190 },
      { label: 'Category', x: 238, width: 80 },
      { label: 'Qty', x: 318, width: 40 },
      { label: 'Unit', x: 358, width: 50 },
      { label: 'Unit Price', x: 408, width: 70 },
      { label: 'Total', x: 488, width: 70 },
    ];

    doc.fontSize(9).fillColor('#555555');
    columns.forEach((col) => doc.text(col.label, col.x, tableTop, { width: col.width }));
    doc.moveTo(48, tableTop + 14).lineTo(547, tableTop + 14).strokeColor('#dddddd').stroke();

    let rowY = tableTop + 20;
    doc.fillColor('#111111');
    (invoice.lineItems || []).forEach((item) => {
      const values = [
        item.description,
        item.category || '-',
        String(item.quantity),
        item.unit || '-',
        money(item.unitPrice),
        money(item.total),
      ];
      columns.forEach((col, index) => {
        doc.text(values[index], col.x, rowY, { width: col.width });
      });
      rowY += 22;
    });

    doc.y = rowY + 8;
    doc.x = 48;
    doc.fontSize(11).fillColor('#111111');
    doc.text(`Subtotal    ${money(invoice.subtotal)}`, { align: 'right' });
    doc.text(`Tax         ${money(invoice.taxAmount)}`, { align: 'right' });
    doc.fontSize(13).text(`Total Due   ${money(invoice.total)}`, { align: 'right' });
    doc.moveDown(1.5);

    doc.fontSize(9).fillColor('#555555');
    doc.text(
      'This invoice is a commercial settlement statement for a DataDance dataset licence. Amounts should match the linked purchase order and wallet payment.',
    );
    doc.moveDown(0.5);
    doc.text('Generated by DataDance commerce. Dataset rows and personal data are not attached to this PDF.');

    doc.end();
    stream.on('finish', resolve);
    stream.on('error', reject);
  });

  await prisma.invoice.update({
    where: { id: invoice.id },
    data: { pdfPath: publicPath },
  });

  return { absolutePath, publicPath };
}

function isCurrentLayout(pdfPath) {
  return typeof pdfPath === 'string' && pdfPath.includes(`.${PDF_LAYOUT_VERSION}.pdf`);
}

async function getOrCreateInvoicePdf(invoice) {
  if (invoice.pdfPath && isCurrentLayout(invoice.pdfPath)) {
    const absolutePath = path.join(__dirname, '../../public', invoice.pdfPath.replace(/^\//, ''));
    if (fs.existsSync(absolutePath)) {
      return { absolutePath, publicPath: invoice.pdfPath };
    }
  }
  return generateInvoicePdf(invoice);
}

module.exports = {
  generateInvoicePdf,
  getOrCreateInvoicePdf,
  PDF_LAYOUT_VERSION,
};
