/**
 * Static partner (TGE) OAuth client, configured from the environment only.
 *
 * There is exactly one pre-registered confidential client per deployment; it never lives in
 * the database, so test and production credentials cannot be copied across environments
 * (contract ddc-sso-tge-v0.1 F01). Everything here is read on demand so a value is never
 * stale and unit tests can set process.env before calling.
 *
 * Secrets: only the sha256 of the client secret is configured (SSO_TGE_CLIENT_SECRET_SHA256).
 * The secret itself is a 32-byte random value generated by scripts/genPartnerSecret.js, so a
 * plain sha256 (no salt/KDF) is adequate. During a rotation the previous hash is accepted
 * until SSO_TGE_SECRET_ROTATION_UNTIL.
 *
 * Nothing in this module logs; the returned client objects never carry secret hashes.
 */
const crypto = require('crypto');
const { getAddress } = require('ethers');
const { publicBaseUrl } = require('./lifeContext');

const PARTNER_KIND = 'partner';
const PARTNER_REALM = 'ddc-sso';
const PARTNER_TOKEN_PREFIX = 'ddc_tge_';
/**
 * Every scope the partner client may request at /oauth/authorize. `tge:identity` (default) and
 * `tge:status` gate an ENDPOINT — missing one is 403 insufficient_scope. The four that follow
 * gate a single FIELD each: a token without them simply does not carry that field, which is why
 * the handlers omit the key instead of answering 403 (a partner that asked for less must still
 * get the rest of the response).
 */
const PARTNER_SCOPES = Object.freeze([
  'tge:identity',
  'tge:status',
  'tge:email',
  'tge:wallet',
  'tge:points',
  'tge:referral',
]);
const PARTNER_DEFAULT_SCOPE = 'tge:identity';
const PARTNER_REQUEST_TTL_MS = 10 * 60 * 1000;
const PARTNER_CODE_TTL_MS = 60 * 1000;
const PARTNER_ACCESS_TTL_SEC = 300;
const PARTNER_STATUS_CACHE_MAX_AGE_SEC = 60;
/** A points balance is never cacheable: it moves on every task, order and referral settlement. */
const PARTNER_POINTS_CACHE_MAX_AGE_SEC = 0;
/** Referral counts move slowly; still short, because an invite is visible to the user at once. */
const PARTNER_REFERRAL_CACHE_MAX_AGE_SEC = 60;
const PARTNER_ENVIRONMENTS = Object.freeze(['test', 'prod']);
const PARTNER_TOKEN_ENDPOINT_AUTH_METHODS = Object.freeze(['client_secret_basic', 'client_secret_post']);
const CLIENT_ID_PATTERN = /^[A-Za-z0-9._-]{1,64}$/;

/**
 * Every field /partner/tge/me and /partner/tge/status can carry, with the two gates in front of
 * it (contract §6, extended for the campaign read API):
 *
 *   1. `scope`  — granted at /oauth/authorize and carried by the token. A field whose scope was
 *                 not granted is OMITTED from the body (`presence: 'omit'`); the call still
 *                 succeeds. Only the endpoint scopes (`tge:identity`, `tge:status`) 403.
 *   2. SSO_TGE_STATUS_FIELDS — the per-environment freeze list. A field that is not listed is
 *                 `null` for the original candidates (`presence: 'null'`, "unknown, never
 *                 fabricated") and OMITTED for the fields added later, so a partner can tell
 *                 "DataDance has nothing" from "this deployment does not serve it".
 *
 * `sub`, `client_id`, `issued_at`, `expires_at`, `account_status`, `as_of` and `cache_max_age`
 * have no gate and are always sent. Default (variable unset): nothing is frozen, so the new
 * fields are OFF until an operator lists them — no code change, no deploy.
 */
const STATUS_FIELD_CATALOG = Object.freeze({
  registered_at: {
    endpoint: 'status',
    scope: 'tge:status',
    presence: 'null',
    source: 'User.createdAt',
    meaning: 'When the DataDance account was created.',
    nullMeaning: 'Not frozen for this environment.',
    cacheTtlSec: PARTNER_STATUS_CACHE_MAX_AGE_SEC,
  },
  wallet_bound: {
    endpoint: 'status',
    scope: 'tge:status',
    presence: 'null',
    source: 'User.walletAddress != null',
    meaning: 'A wallet address is bound to the account. Not proof of control, not a signing permission.',
    nullMeaning: 'Unknown / not frozen.',
    cacheTtlSec: PARTNER_STATUS_CACHE_MAX_AGE_SEC,
  },
  data_licence_granted: {
    endpoint: 'status',
    scope: 'tge:status',
    presence: 'null',
    source: 'DataLicenceConsent active (grantedAt set, not withdrawn, current policy version)',
    meaning: 'The user allowed DataDance to license their Connect records. Unrelated to partner eligibility.',
    nullMeaning: 'Unknown / not frozen.',
    cacheTtlSec: PARTNER_STATUS_CACHE_MAX_AGE_SEC,
  },
  email_masked: {
    endpoint: 'me',
    scope: 'tge:identity',
    presence: 'null',
    source: 'User.email masked as j***@domain.com',
    meaning: 'Display hint for the partner; never an identifier.',
    nullMeaning: 'No e-mail on the account, not a real address, or not frozen.',
    cacheTtlSec: 0,
  },
  email: {
    endpoint: 'me',
    scope: 'tge:email',
    presence: 'omit',
    source: 'User.email, when it really is an e-mail address',
    meaning: "The user's e-mail address, as the campaign will write to it.",
    nullMeaning:
      'The account has no e-mail: an external-wallet login stores the lower-cased wallet address in the NOT NULL e-mail column and a legacy X login stored `twitter|<id>` there. Neither is an address.',
    cacheTtlSec: 0,
  },
  wallet_address: {
    endpoint: 'me',
    scope: 'tge:wallet',
    presence: 'omit',
    source: 'User.walletAddress, EIP-55 checksummed when it parses',
    meaning:
      'The wallet bound to the account, for an on-chain distribution. Still not proof of control and not a permission to sign or transfer (F05).',
    nullMeaning: 'No wallet is bound to the account.',
    cacheTtlSec: 0,
  },
  points: {
    endpoint: 'status',
    scope: 'tge:points',
    presence: 'omit',
    source: 'User.totalPoints (denormalised balance; the Point ledger is the source of truth)',
    meaning: '{ balance, as_of, cache_max_age }. The DataDance points balance at `as_of`.',
    nullMeaning: 'Never null while granted and frozen; a fresh account is `balance: 0`.',
    cacheTtlSec: PARTNER_POINTS_CACHE_MAX_AGE_SEC,
  },
  referral: {
    endpoint: 'status',
    scope: 'tge:referral',
    presence: 'omit',
    source: 'User.referralCode + Referral rows for this user (inviteeId for the inviter, level-1 inviterId count)',
    meaning:
      '{ code, inviter_sub, direct_invitees }. One id (the inviter, so the partner can pay an upline rebate) and one count (for a leaderboard). No downline list, no multi-level total.',
    nullMeaning:
      '`inviter_sub` is null when nobody invited this user; `code` is null when a display code could not be resolved.',
    cacheTtlSec: PARTNER_REFERRAL_CACHE_MAX_AGE_SEC,
  },
});
const DEFAULT_STATUS_FIELDS = Object.freeze([]);

function csv(value) {
  return String(value || '')
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
}

function flag(value) {
  return String(value || '').trim().toLowerCase() === 'true';
}

function normalizeHash(value) {
  const hex = String(value || '').trim().toLowerCase();
  return /^[0-9a-f]{64}$/.test(hex) ? hex : '';
}

function parseDate(value) {
  const raw = String(value || '').trim();
  if (!raw) return null;
  const date = new Date(raw);
  return Number.isNaN(date.getTime()) ? null : date;
}

function sha256Hex(value) {
  return crypto.createHash('sha256').update(String(value)).digest('hex');
}

function hashesEqual(a, b) {
  if (!a || !b || a.length !== b.length) return false;
  return crypto.timingSafeEqual(Buffer.from(a, 'hex'), Buffer.from(b, 'hex'));
}

/** Parses every SSO_TGE_* / SSO_* variable; never logged as a whole (contains hashes). */
function readPartnerConfig(env = process.env) {
  return {
    environment: String(env.SSO_ENVIRONMENT || '').trim(),
    enabled: flag(env.SSO_TGE_ENABLED),
    clientId: String(env.SSO_TGE_CLIENT_ID || '').trim(),
    clientName: String(env.SSO_TGE_CLIENT_NAME || '').trim() || 'TGE',
    secretHash: normalizeHash(env.SSO_TGE_CLIENT_SECRET_SHA256),
    previousSecretHash: normalizeHash(env.SSO_TGE_CLIENT_SECRET_SHA256_PREVIOUS),
    rotationUntil: parseDate(env.SSO_TGE_SECRET_ROTATION_UNTIL),
    redirectUris: csv(env.SSO_TGE_REDIRECT_URIS),
    initiateLoginUri: String(env.SSO_TGE_INITIATE_LOGIN_URI || '').trim(),
    statusFields: env.SSO_TGE_STATUS_FIELDS === undefined ? [...DEFAULT_STATUS_FIELDS] : csv(env.SSO_TGE_STATUS_FIELDS),
    requireVerifiedSession: flag(env.SSO_REQUIRE_VERIFIED_SESSION),
  };
}

/** Audience of partner access tokens: `${PUBLIC_BASE_URL}/partner/tge` (same convention as `/mcp`). */
function partnerResourceUrl(req) {
  let base = '';
  if (req && typeof req.get === 'function') {
    base = publicBaseUrl(req);
  } else {
    base = (process.env.PUBLIC_BASE_URL || '').trim().replace(/\/$/, '') || `http://localhost:${process.env.PORT || 3000}`;
  }
  return `${base}/partner/tge`;
}

/**
 * The one static client, or null when none is configured / the id does not match.
 * `getPartnerClient()` (no id) returns the configured client regardless of id.
 * A disabled client is still returned (enabled: false) so callers can answer
 * `unauthorized_client` / `invalid_client` instead of "unknown".
 * The returned object never carries secret hashes.
 */
function getPartnerClient(clientId, req) {
  const cfg = readPartnerConfig();
  if (!cfg.clientId) return null;
  if (clientId !== undefined && clientId !== null && String(clientId) !== cfg.clientId) return null;
  return {
    kind: PARTNER_KIND,
    clientId: cfg.clientId,
    clientName: cfg.clientName,
    enabled: cfg.enabled,
    environment: cfg.environment,
    redirectUris: [...cfg.redirectUris],
    initiateLoginUri: cfg.initiateLoginUri,
    tokenEndpointAuthMethod: 'client_secret_basic',
    tokenEndpointAuthMethods: [...PARTNER_TOKEN_ENDPOINT_AUTH_METHODS],
    resource: partnerResourceUrl(req),
    scopes: [...PARTNER_SCOPES],
    defaultScope: PARTNER_DEFAULT_SCOPE,
    requestTtlMs: PARTNER_REQUEST_TTL_MS,
    codeTtlMs: PARTNER_CODE_TTL_MS,
    accessTtlSec: PARTNER_ACCESS_TTL_SEC,
    statusFields: [...cfg.statusFields],
    requireVerifiedSession: cfg.requireVerifiedSession,
  };
}

function isPartnerClient(client) {
  return Boolean(client && client.kind === PARTNER_KIND);
}

/**
 * sha256(secret) against the current hash, or the previous hash while the rotation window is
 * open. Constant-time comparison; both candidates are always evaluated.
 */
function verifyClientSecret(client, secret, { now = Date.now() } = {}) {
  if (!client || typeof secret !== 'string' || !secret || secret.length > 1024) return false;
  const cfg = readPartnerConfig();
  if (!cfg.clientId || client.clientId !== cfg.clientId) return false;
  const presented = sha256Hex(secret);
  const currentOk = hashesEqual(presented, cfg.secretHash);
  const rotationOpen = Boolean(cfg.previousSecretHash && cfg.rotationUntil && now < cfg.rotationUntil.getTime());
  const previousOk = hashesEqual(presented, cfg.previousSecretHash) && rotationOpen;
  return currentOk || previousOk;
}

/** RFC 6749 §2.3.1: each half is form-urlencoded before base64; decode after splitting. */
function decodeFormComponent(value) {
  try {
    return decodeURIComponent(String(value).replace(/\+/g, ' '));
  } catch {
    // A client that did not encode its credential at all: use it verbatim.
    return String(value);
  }
}

/**
 * Parses `Authorization: Basic <base64(urlencode(client_id):urlencode(client_secret))>`.
 * Returns { clientId, clientSecret } or null when the header is not well-formed Basic.
 */
function parseBasicAuth(headerValue) {
  const match = /^Basic\s+([A-Za-z0-9+/=_-]+)\s*$/i.exec(String(headerValue || ''));
  if (!match) return null;
  const decoded = Buffer.from(match[1], 'base64').toString('utf8');
  const idx = decoded.indexOf(':');
  if (idx < 0) return null;
  return {
    clientId: decodeFormComponent(decoded.slice(0, idx)),
    clientSecret: decodeFormComponent(decoded.slice(idx + 1)),
  };
}

/**
 * `User.email` is NOT NULL, so logins that have no e-mail park something else in it:
 *  - an external-wallet login stores the lower-cased wallet address (see EXTERNAL_WALLET_VERIFIER
 *    in src/services/web3authIdentity.js — mirrored here rather than imported, because that
 *    module pulls jose and its own boot configuration into a constants file);
 *  - a legacy X login stored the IdP subject `twitter|<id>`.
 * Neither is an address a campaign could write to, so both read as "no e-mail".
 */
const EXTERNAL_WALLET_VERIFIER = 'external-wallet';
const IDP_SUBJECT_PATTERN = /^[a-z0-9-]+\|/i;
const RAW_ADDRESS_PATTERN = /^0x[0-9a-fA-F]{40}$/;

/** The real e-mail address, or null when the column holds one of the placeholders above. */
function realEmail(user) {
  const value = String((user && user.email) || '').trim();
  if (!value) return null;
  if (user && user.web3authVerifier === EXTERNAL_WALLET_VERIFIER) return null;
  if (IDP_SUBJECT_PATTERN.test(value) || RAW_ADDRESS_PATTERN.test(value)) return null;
  const at = value.indexOf('@');
  if (at < 1 || at === value.length - 1) return null;
  return value;
}

/** `j***@domain.com`; null when there is no usable e-mail. */
function maskEmail(email) {
  const value = String(email || '').trim();
  const at = value.indexOf('@');
  if (at < 1 || at === value.length - 1) return null;
  return `${value[0]}***@${value.slice(at + 1)}`;
}

/**
 * EIP-55 checksum form, so the partner can compare addresses byte-for-byte with what a wallet
 * shows. A stored value that ethers cannot parse is handed back verbatim rather than dropped:
 * it is what DataDance holds, and inventing a "valid" address would be worse than an odd one.
 */
function checksumWalletAddress(address) {
  const value = String(address || '').trim();
  if (!value) return null;
  try {
    return getAddress(value);
  } catch {
    return value;
  }
}

function isLoopbackHost(hostname) {
  return hostname === 'localhost' || hostname === '127.0.0.1' || hostname === '[::1]';
}

function redirectUriProblem(uri, production) {
  let parsed;
  try {
    parsed = new URL(uri);
  } catch {
    return `"${uri}" is not an absolute URL`;
  }
  if (parsed.protocol !== 'https:' && parsed.protocol !== 'http:') return `"${uri}" must use http(s)`;
  if (uri.includes('#')) return `"${uri}" must not contain a fragment`;
  if (parsed.protocol === 'http:' && (production || !isLoopbackHost(parsed.hostname))) {
    return `"${uri}" must be https (http is only accepted for localhost outside production)`;
  }
  return '';
}

/**
 * Boot-time validation (called from src/server.js). Throws a single Error listing every
 * problem so a misconfigured container never serves the partner flow half-configured.
 * Returns a secret-free summary for the boot log.
 */
function assertPartnerConfig(env = process.env) {
  const cfg = readPartnerConfig(env);
  const production = env.NODE_ENV === 'production' || cfg.environment === 'prod';
  const problems = [];

  if (cfg.environment && !PARTNER_ENVIRONMENTS.includes(cfg.environment)) {
    problems.push(`SSO_ENVIRONMENT must be one of ${PARTNER_ENVIRONMENTS.join('|')} (got "${cfg.environment}")`);
  }
  if (cfg.enabled) {
    if (!PARTNER_ENVIRONMENTS.includes(cfg.environment)) {
      problems.push(`SSO_ENVIRONMENT must be ${PARTNER_ENVIRONMENTS.join('|')} when SSO_TGE_ENABLED=true`);
    }
    if (!cfg.clientId) problems.push('SSO_TGE_CLIENT_ID is required');
    else if (!CLIENT_ID_PATTERN.test(cfg.clientId)) {
      problems.push('SSO_TGE_CLIENT_ID must match [A-Za-z0-9._-]{1,64} (no URL, no ":")');
    }
    if (!cfg.secretHash) problems.push('SSO_TGE_CLIENT_SECRET_SHA256 must be the 64-hex sha256 of the client secret');
    if (env.SSO_TGE_CLIENT_SECRET_SHA256_PREVIOUS && !cfg.previousSecretHash) {
      problems.push('SSO_TGE_CLIENT_SECRET_SHA256_PREVIOUS must be a 64-hex sha256');
    }
    if (cfg.previousSecretHash && !cfg.rotationUntil) {
      problems.push('SSO_TGE_SECRET_ROTATION_UNTIL (ISO-8601) is required while SSO_TGE_CLIENT_SECRET_SHA256_PREVIOUS is set');
    }
    if (!cfg.redirectUris.length) problems.push('SSO_TGE_REDIRECT_URIS must list at least one redirect URI');
    for (const uri of cfg.redirectUris) {
      const problem = redirectUriProblem(uri, production);
      if (problem) problems.push(`SSO_TGE_REDIRECT_URIS: ${problem}`);
    }
    if (cfg.initiateLoginUri) {
      const problem = redirectUriProblem(cfg.initiateLoginUri, production);
      if (problem) problems.push(`SSO_TGE_INITIATE_LOGIN_URI: ${problem}`);
    }
    for (const field of cfg.statusFields) {
      if (!STATUS_FIELD_CATALOG[field]) problems.push(`SSO_TGE_STATUS_FIELDS: unknown field "${field}"`);
    }
    // Phase 3: the consent-only SSO session is safe only because it is signed with a key the
    // normal session middleware does not know. Same key = the session would open every
    // authenticated endpoint. Never log either value.
    const sessionSecret = String(env.SSO_SESSION_SECRET || '').trim();
    if (!sessionSecret) {
      problems.push('SSO_SESSION_SECRET is required when SSO_TGE_ENABLED=true (dedicated key for the App hand-off session)');
    } else if (sessionSecret === String(env.JWT_SECRET || '').trim()) {
      problems.push('SSO_SESSION_SECRET must differ from JWT_SECRET');
    }
    if (production) {
      if (!String(env.PUBLIC_BASE_URL || '').trim()) problems.push('PUBLIC_BASE_URL is required in production');
      if (!String(env.APP_PUBLIC_URL || '').trim()) problems.push('APP_PUBLIC_URL is required in production');
    }
  }

  if (problems.length) {
    throw new Error(`Partner (TGE) SSO configuration is invalid:\n - ${problems.join('\n - ')}`);
  }
  return {
    enabled: cfg.enabled,
    environment: cfg.environment,
    clientId: cfg.clientId,
    redirectUriCount: cfg.redirectUris.length,
    statusFields: [...cfg.statusFields],
    requireVerifiedSession: cfg.requireVerifiedSession,
    rotationOpen: Boolean(cfg.previousSecretHash && cfg.rotationUntil && Date.now() < cfg.rotationUntil.getTime()),
  };
}

module.exports = {
  PARTNER_KIND,
  PARTNER_REALM,
  PARTNER_TOKEN_PREFIX,
  PARTNER_SCOPES,
  PARTNER_DEFAULT_SCOPE,
  PARTNER_REQUEST_TTL_MS,
  PARTNER_CODE_TTL_MS,
  PARTNER_ACCESS_TTL_SEC,
  PARTNER_STATUS_CACHE_MAX_AGE_SEC,
  PARTNER_POINTS_CACHE_MAX_AGE_SEC,
  PARTNER_REFERRAL_CACHE_MAX_AGE_SEC,
  PARTNER_ENVIRONMENTS,
  PARTNER_TOKEN_ENDPOINT_AUTH_METHODS,
  STATUS_FIELD_CATALOG,
  DEFAULT_STATUS_FIELDS,
  readPartnerConfig,
  partnerResourceUrl,
  getPartnerClient,
  isPartnerClient,
  verifyClientSecret,
  parseBasicAuth,
  parseBasicCredentials: parseBasicAuth,
  maskEmail,
  realEmail,
  checksumWalletAddress,
  EXTERNAL_WALLET_VERIFIER,
  sha256Hex,
  assertPartnerConfig,
};
